const database = [
    {q:"Are you easily embarrassed or shamed?",
     category:"rejection"},
    {q:"Do you find yourself frequently pulling away from others?",
    category:"rejection"},
    {q:"Do you have extreme responses of anger or emotional outburst when you feel that someone has hurt or rejected you?",
     category:"rejection"},
    {q:"Do you battle with low self-esteem?",
    category:"rejection"},
    {q:"Are you easily offended?",
    category:"rejection"},
    {q:"Do you battle with feelings of not feeling wanted?",
    category:"abandonment"},
    {q:"Do you always expect persons to leave you or walk out of your life eventually?",
     category:"abandonment"},
    {q:"Do you find yourself being eager to please others?",
    category:"abandonment"},
    {q:"Do you stayin dsyfunctional relationships even when you desire to leave or know it's toxic?",
     category:"abandonment"},
    {q:"Do you find yourself feeling insecure about your friendships and other relationships?",
    category:"abandonment"},
    {q:"Do you easily and normally hold grudges?",
    category:"trust"},
    {q:"Do you feel as though you have to do everything yourself because the only person you can depend on is yourself?",
    category:"trust"},
    {q:"Do you find it difficult in commit in relationships?",
    category:"trust"},
    {q:"Do you avoid intimacy and vulnerability at all costs?",
     category:"trust"},
    {q:"Do you have a history of sabotaging your relationships?",
    category:"trust"},
]

export default database;